### ISSUE TITLE
An IoT device is securely connected to the internet

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#10]
- [x]  An IoT device is securely connected to the internet

**Comment by OliwierJaworski** [comment]
the IoT device (Pynq) can only be accessed using a ssh-key that has been put into the authorized folder 

![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114076196/33f92f57-cae6-463d-9667-a702ce0bbe64)

example of an unauthorized user trying to access the device

![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114076196/c241ff82-60b8-4bba-86ab-b936d5c37fee)

settings for the ssh service

![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114076196/65ea8c25-c260-4624-a2cb-73f739967218)

**Comment by MauroDeBruyn** [comment]
All SSH public keys of the contributors are added and transferred from the test-server to the final server
