### ISSUE TITLE
An IoT device of which the application software automatically updates itself (OTA)

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#11]
- [ ]  An IoT device of which the application software automatically updates itself (OTA)

**Comment by OliwierJaworski** [comment]
With the use of portainer.io to monitor the containers and the use of watchtower in docker i was able to create the first implementation of the over air update in which the watchtower container updates all the other containers every 30 ish seconds
![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114076196/3217ba71-2a81-4c2b-9dda-b488d155d57c)

**Comment by OliwierJaworski** [comment]
dropped the use of watchtower

**Comment by OliwierJaworski** [comment]
- [x] application is updated over the air using github actions and a bash scripts
-responsible script for the over the air update can be found in the branch xilinx-scripts
-The github action can be found in the main branch under the name app_deployment.yml
