### ISSUE TITLE
The application software is capable of speaking to an HTTPS CRUD endpoint

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#14]
- [ ]  The application software is capable of speaking to an HTTPS CRUD endpoint

**Comment by RunarJans** [comment]
On the branch "RunarDev" you can find the file "server_put_req_working.py" this python script is responsible for speaking to an https crud endpoint

**Comment by MauroDeBruyn** [comment]
The code provided on my branch was used to get temp from the pynq and to send the data to the database. @OliwierJaworski changed the path and API key to deploy the code on the server.
