### ISSUE TITLE
The application software is automatically built

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#19]
- [x]  The application software is automatically built

**Comment by ThibeVanOrshaegen** [comment]
Via github actions and the docker file, the software is automatically built 
![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114075982/ecc5a166-ed6c-4b8b-94c2-966b9fefe67c)

**Comment by ThibeVanOrshaegen** [comment]
This is done here.
This is done here.
![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114075982/68462403-9591-4dc0-8f24-01f10860dfa9)

**Comment by OliwierJaworski** [comment]
fixed some compatibility issue in the github actions with the arm32v7 acrhitecture the most recent commit made in main 
that contains the following changes:
- [x] The following github action is used for pushing multi platform images
```
docker/setup-buildx-action@v3
```
- [x] The following github action enables emulation for different CPU architectures in Docker builds.
 ```
docker/setup-qemu-action@v3
```
