### ISSUE TITLE
The application software uses Python and uses Poetry as a dependency manager

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#24]
- [ ]  The application software uses Python and uses [Poetry](https://python-poetry.org/) as a dependency manager

**Comment by ThibeVanOrshaegen** [comment]
# Step to use Poetry
## Install Poetry
Use one of these commands
curl -sSL https://install.python-poetry.org | python3 -
or
pip install poetry

**Comment by OliwierJaworski** [comment]
Problems with installing poetry inside a docker container may have something to do with dependencies or arm32/v7

**Comment by OliwierJaworski** [comment]
due to difficulties with the installation in the docker process the decision was made to drop this item from the to-do list
