### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#29]
I cannot start a workflow in this repository. I think because I am not the owner. I have tried this in 4 respositorys of mine and every one of them went. So I think @OliwierJaworski  should delete this workflow file for a while and add it back. Once this is done you need to go to setting, go to Secrets and variables. 
You need to add two, one as DOCKER_USERNAME in this should be thibeeeeee, and the second DOCKER_PASSWORD is Zinou2006! then it should automatically log into the docker account. Once it has gone through all this workflow, it has automatically built and packaged the application software as a docker format, an image.

@MauroDeBruyn @RunarJans @OliwierJaworski  can also use this data to log into the Docker hub to see if it succeeded.

**Comment by OliwierJaworski** [comment]
fixed by changing the workspace to "main" instead of "master"
