### ISSUE TITLE
An IoT device is connected to the internet

### ISSUE THREAD

**Issue by ThibeVanOrshaegen** [OliwierJaworski/EindOpdracht-IoT-Technologie#8]
- [x]  An IoT device is connected to the internet

**Comment by ThibeVanOrshaegen** [comment]
This has been solved by using these links https://www.nengo.ai/nengo-pynq/connect.html#via-a-computer and https://www.nengo.ai/nengo-pynq/appendix.html#board-static-ip

**Comment by ThibeVanOrshaegen** [comment]
![image](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/114075982/293d3f94-0465-4c68-b829-ab8707060389)

**Comment by MauroDeBruyn** [comment]
![image_2024-01-06_170124662](https://github.com/OliwierJaworski/EindOpdracht-IoT-Technologie/assets/99724559/6fd713b2-9c80-4b7d-b711-1a9cbbd6978a)

Port forwarding for pynq
